name: rust
on: [push, pull_request]
jobs:
  test:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-test.yaml@main
    secrets: inherit
  static:
    uses: rainlanguage/rainix/.github/workflows/rainix-rs-static.yaml@main
    secrets: inherit
